version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 10
    reviewers:
      - "@astral-core/maintainers"
    assignees:
      - "@astral-core/maintainers"
    commit-message:
      prefix: "deps"
      include: "scope"
    ignore:
      # Ignore major version updates for critical dependencies
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@prisma/client"
        update-types: ["version-update:semver-major"]
      - dependency-name: "prisma"
        update-types: ["version-update:semver-major"]
    groups:
      # Group testing dependencies
      testing:
        patterns:
          - "@testing-library/*"
          - "jest*"
          - "@jest/*"
          - "playwright*"
        update-types:
          - "minor"
          - "patch"
      
      # Group TypeScript and related tooling
      typescript:
        patterns:
          - "typescript"
          - "@types/*"
          - "@typescript-eslint/*"
        update-types:
          - "minor"
          - "patch"
      
      # Group linting and formatting
      linting:
        patterns:
          - "eslint*"
          - "@eslint/*"
          - "prettier"
        update-types:
          - "minor"
          - "patch"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
    open-pull-requests-limit: 5
    reviewers:
      - "@astral-core/devops"
    assignees:
      - "@astral-core/devops"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 3
    reviewers:
      - "@astral-core/devops"
    assignees:
      - "@astral-core/devops"
    commit-message:
      prefix: "docker"
      include: "scope"